# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import background
import os, sys
import numpy as np
import pandas as pd
import h5py as h
import recommender

# pyuic5 -x main_window.ui -o gui.py
# Pyrcc5 input_file.qrc -o icons.py

class Ui_MainWindow(object):

    books_displayed = 0
    rec_books_displayed = 0
    current_ids = []
    user_ratings = []
    books_to_display = []
    recommended_bools = []
    rec_books_num = 0
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Book Recommender")
        MainWindow.resize(770, 678)
        MainWindow.setMaximumSize(QtCore.QSize(770, 678))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(780, 680))
        self.centralwidget.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 771, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 719))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_getRec = QtWidgets.QPushButton(self.page)
        self.pushButton_getRec.setGeometry(QtCore.QRect(170, 520, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton_getRec.setFont(font)
        self.pushButton_getRec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_getRec.setObjectName("pushButton_getRec")
        self.label_hello = QtWidgets.QLabel(self.page)
        self.label_hello.setGeometry(QtCore.QRect(210, 140, 331, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(44)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_hello.setFont(font)
        self.label_hello.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_hello.setScaledContents(True)
        self.label_hello.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hello.setObjectName("label_hello")
        self.graphicsView_background = QtWidgets.QGraphicsView(self.page)
        self.graphicsView_background.setGeometry(QtCore.QRect(-1, -1, 771, 681))
        self.graphicsView_background.setStyleSheet("background:url(:/newPrefix/digital-book.jpg)")
        self.graphicsView_background.setObjectName("graphicsView_background")
        self.graphicsView_background.raise_()
        self.pushButton_getRec.raise_()
        self.label_hello.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_rate = QtWidgets.QLabel(self.page_2)
        self.label_rate.setGeometry(QtCore.QRect(30, 20, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_rate.setFont(font)
        self.label_rate.setStyleSheet("background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_rate.setObjectName("label_rate")
        self.pushButton_more = QtWidgets.QPushButton(self.page_2)
        self.pushButton_more.setGeometry(QtCore.QRect(90, 620, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_more.setFont(font)
        self.pushButton_more.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_more.setObjectName("pushButton_more")
        self.pushButton_done = QtWidgets.QPushButton(self.page_2)
        self.pushButton_done.setGeometry(QtCore.QRect(350, 620, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_done.setFont(font)
        self.pushButton_done.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_done.setObjectName("pushButton_done")
        self.widget_rate = QtWidgets.QWidget(self.page_2)
        self.widget_rate.setGeometry(QtCore.QRect(20, 60, 731, 541))
        self.widget_rate.setStyleSheet("background:transparent;")
        self.widget_rate.setObjectName("widget_rate")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_rate)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_1 = QtWidgets.QWidget(self.widget_rate)
        self.widget_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_1.setObjectName("widget_1")
        self.label_title_1 = QtWidgets.QLabel(self.widget_1)
        self.label_title_1.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_1.sizePolicy().hasHeightForWidth())
        self.label_title_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_1.setFont(font)
        self.label_title_1.setAcceptDrops(False)
        self.label_title_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_1.setScaledContents(False)
        self.label_title_1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_1.setWordWrap(True)
        self.label_title_1.setObjectName("label_title_1")
        self.label_rating_1 = QtWidgets.QLabel(self.widget_1)
        self.label_rating_1.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_1.setFont(font)
        self.label_rating_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_1.setObjectName("label_rating_1")
        self.spinBox_rating_1 = QtWidgets.QSpinBox(self.widget_1)
        self.spinBox_rating_1.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_1.setFont(font)
        self.spinBox_rating_1.setMaximum(5)
        self.spinBox_rating_1.setObjectName("spinBox_rating_1")
        self.label_cover_1 = QtWidgets.QLabel(self.widget_1)
        self.label_cover_1.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_1.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_1.setObjectName("label_cover_1")
        self.gridLayout.addWidget(self.widget_1, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_rate)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.label_title_5 = QtWidgets.QLabel(self.widget_5)
        self.label_title_5.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_5.sizePolicy().hasHeightForWidth())
        self.label_title_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_5.setFont(font)
        self.label_title_5.setAcceptDrops(False)
        self.label_title_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_5.setScaledContents(False)
        self.label_title_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_5.setWordWrap(True)
        self.label_title_5.setObjectName("label_title_5")
        self.label_rating_5 = QtWidgets.QLabel(self.widget_5)
        self.label_rating_5.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_5.setFont(font)
        self.label_rating_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_5.setObjectName("label_rating_5")
        self.spinBox_rating_5 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_rating_5.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_5.setFont(font)
        self.spinBox_rating_5.setMaximum(5)
        self.spinBox_rating_5.setObjectName("spinBox_rating_5")
        self.label_cover_5 = QtWidgets.QLabel(self.widget_5)
        self.label_cover_5.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_5.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_5.setText("")
        #self.label_cover_5.setObjectName("label_cover_5")
        self.gridLayout.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_rate)
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_title_3 = QtWidgets.QLabel(self.widget_3)
        self.label_title_3.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_3.sizePolicy().hasHeightForWidth())
        self.label_title_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_3.setFont(font)
        self.label_title_3.setAcceptDrops(False)
        self.label_title_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_3.setScaledContents(False)
        self.label_title_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_3.setWordWrap(True)
        self.label_title_3.setObjectName("label_title_3")
        self.label_rating_3 = QtWidgets.QLabel(self.widget_3)
        self.label_rating_3.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_3.setFont(font)
        self.label_rating_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_3.setObjectName("label_rating_3")
        self.spinBox_rating_3 = QtWidgets.QSpinBox(self.widget_3)
        self.spinBox_rating_3.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_3.setFont(font)
        self.spinBox_rating_3.setMinimum(0)
        self.spinBox_rating_3.setMaximum(5)
        self.spinBox_rating_3.setProperty("value", 0)
        self.spinBox_rating_3.setObjectName("spinBox_rating_3")
        self.label_cover_3 = QtWidgets.QLabel(self.widget_3)
        self.label_cover_3.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_3.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_3.setText("")
        #self.label_cover_3.setObjectName("label_cover_3")
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_rate)
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.label_title_4 = QtWidgets.QLabel(self.widget_4)
        self.label_title_4.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_4.sizePolicy().hasHeightForWidth())
        self.label_title_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_4.setFont(font)
        self.label_title_4.setAcceptDrops(False)
        self.label_title_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_4.setScaledContents(False)
        self.label_title_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_4.setWordWrap(True)
        self.label_title_4.setObjectName("label_title_4")
        self.label_rating_4 = QtWidgets.QLabel(self.widget_4)
        self.label_rating_4.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_4.setFont(font)
        self.label_rating_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_4.setObjectName("label_rating_4")
        self.spinBox_rating_4 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_rating_4.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_4.setFont(font)
        self.spinBox_rating_4.setMaximum(5)
        self.spinBox_rating_4.setObjectName("spinBox_rating_4")
        self.label_cover_4 = QtWidgets.QLabel(self.widget_4)
        self.label_cover_4.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_4.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_4.setText("")
        #self.label_cover_4.setObjectName("label_cover_4")
        self.gridLayout.addWidget(self.widget_4, 0, 3, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_rate)
        self.widget_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_8.setObjectName("widget_8")
        self.label_title_8 = QtWidgets.QLabel(self.widget_8)
        self.label_title_8.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_8.sizePolicy().hasHeightForWidth())
        self.label_title_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_8.setFont(font)
        self.label_title_8.setAcceptDrops(False)
        self.label_title_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_8.setScaledContents(False)
        self.label_title_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_8.setWordWrap(True)
        self.label_title_8.setObjectName("label_title_8")
        self.label_rating_8 = QtWidgets.QLabel(self.widget_8)
        self.label_rating_8.setGeometry(QtCore.QRect(20, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_8.setFont(font)
        self.label_rating_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_8.setObjectName("label_rating_8")
        self.spinBox_rating_8 = QtWidgets.QSpinBox(self.widget_8)
        self.spinBox_rating_8.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_8.setFont(font)
        self.spinBox_rating_8.setMaximum(5)
        self.spinBox_rating_8.setObjectName("spinBox_rating_8")
        self.label_cover_8 = QtWidgets.QLabel(self.widget_8)
        self.label_cover_8.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_8.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_8.setText("")
        #self.label_cover_8.setObjectName("label_cover_8")
        self.gridLayout.addWidget(self.widget_8, 1, 3, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_rate)
        self.widget_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_7.setObjectName("widget_7")
        self.label_title_7 = QtWidgets.QLabel(self.widget_7)
        self.label_title_7.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_7.sizePolicy().hasHeightForWidth())
        self.label_title_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_7.setFont(font)
        self.label_title_7.setAcceptDrops(False)
        self.label_title_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_7.setScaledContents(False)
        self.label_title_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_7.setWordWrap(True)
        self.label_title_7.setObjectName("label_title_7")
        self.label_rating_7 = QtWidgets.QLabel(self.widget_7)
        self.label_rating_7.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_7.setFont(font)
        self.label_rating_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_7.setObjectName("label_rating_7")
        self.spinBox_rating_7 = QtWidgets.QSpinBox(self.widget_7)
        self.spinBox_rating_7.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_7.setFont(font)
        self.spinBox_rating_7.setMaximum(5)
        self.spinBox_rating_7.setObjectName("spinBox_rating_7")
        self.label_cover_7 = QtWidgets.QLabel(self.widget_7)
        self.label_cover_7.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_7.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_7.setText("")
        #self.label_cover_7.setObjectName("label_cover_7")
        self.gridLayout.addWidget(self.widget_7, 1, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_rate)
        self.widget_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.label_title_6 = QtWidgets.QLabel(self.widget_6)
        self.label_title_6.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_6.sizePolicy().hasHeightForWidth())
        self.label_title_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_6.setFont(font)
        self.label_title_6.setAcceptDrops(False)
        self.label_title_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_6.setScaledContents(False)
        self.label_title_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_6.setWordWrap(True)
        self.label_title_6.setObjectName("label_title_6")
        self.label_rating_6 = QtWidgets.QLabel(self.widget_6)
        self.label_rating_6.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_6.setFont(font)
        self.label_rating_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_6.setObjectName("label_rating_6")
        self.spinBox_rating_6 = QtWidgets.QSpinBox(self.widget_6)
        self.spinBox_rating_6.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_6.setFont(font)
        self.spinBox_rating_6.setMaximum(5)
        self.spinBox_rating_6.setObjectName("spinBox_rating_6")
        self.label_cover_6 = QtWidgets.QLabel(self.widget_6)
        self.label_cover_6.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_6.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_6.setText("")
        #self.label_cover_6.setObjectName("label_cover_6")
        self.gridLayout.addWidget(self.widget_6, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_rate)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.label_title_2 = QtWidgets.QLabel(self.widget_2)
        self.label_title_2.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_2.sizePolicy().hasHeightForWidth())
        self.label_title_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_2.setFont(font)
        self.label_title_2.setAcceptDrops(False)
        self.label_title_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_2.setScaledContents(False)
        self.label_title_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_2.setWordWrap(True)
        self.label_title_2.setObjectName("label_title_2")
        self.label_rating_2 = QtWidgets.QLabel(self.widget_2)
        self.label_rating_2.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_rating_2.setFont(font)
        self.label_rating_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rating_2.setObjectName("label_rating_2")
        self.spinBox_rating_2 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_rating_2.setGeometry(QtCore.QRect(100, 220, 42, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_rating_2.setFont(font)
        self.spinBox_rating_2.setMaximum(5)
        self.spinBox_rating_2.setObjectName("spinBox_rating_2")
        self.label_cover_2 = QtWidgets.QLabel(self.widget_2)
        self.label_cover_2.setGeometry(QtCore.QRect(40, 10, 98, 146))
        #self.label_cover_2.setStyleSheet("background-color: rgb(207, 207, 207);")
        #self.label_cover_2.setText("")
        #self.label_cover_2.setObjectName("label_cover_2")
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.graphicsView_background_2 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_background_2.setGeometry(QtCore.QRect(-1, -1, 771, 681))
        self.graphicsView_background_2.setStyleSheet("background:url(:/newPrefix/digital-book.jpg)")
        self.graphicsView_background_2.setObjectName("graphicsView_background_2")
        self.graphicsView_background_2.raise_()
        self.label_rate.raise_()
        self.pushButton_more.raise_()
        self.pushButton_done.raise_()
        self.widget_rate.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_like = QtWidgets.QLabel(self.page_3)
        self.label_like.setGeometry(QtCore.QRect(30, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_like.setFont(font)
        self.label_like.setStyleSheet("background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_like.setObjectName("label_like")
        self.widget_recommendations = QtWidgets.QWidget(self.page_3)
        self.widget_recommendations.setGeometry(QtCore.QRect(20, 60, 731, 541))
        self.widget_recommendations.setStyleSheet("background: transparent;")
        self.widget_recommendations.setObjectName("widget_recommendations")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_recommendations)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_10 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_10.setObjectName("widget_10")
        self.label_title_10 = QtWidgets.QLabel(self.widget_10)
        self.label_title_10.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_10.sizePolicy().hasHeightForWidth())
        self.label_title_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_10.setFont(font)
        self.label_title_10.setAcceptDrops(False)
        self.label_title_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_10.setScaledContents(False)
        self.label_title_10.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_10.setWordWrap(True)
        self.label_title_10.setObjectName("label_title_10")
        self.label_averageNum_10 = QtWidgets.QLabel(self.widget_10)
        self.label_averageNum_10.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_10.setFont(font)
        self.label_averageNum_10.setObjectName("label_averageNum_10")
        self.label_average_10 = QtWidgets.QLabel(self.widget_10)
        self.label_average_10.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_10.setFont(font)
        self.label_average_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_10.setObjectName("label_average_10")
        self.label_cover_10 = QtWidgets.QLabel(self.widget_10)
        self.label_cover_10.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_10.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_10.setText("")
        self.label_cover_10.setObjectName("label_cover_10")
        self.gridLayout_2.addWidget(self.widget_10, 0, 1, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_16.setObjectName("widget_16")
        self.label_title_16 = QtWidgets.QLabel(self.widget_16)
        self.label_title_16.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_16.sizePolicy().hasHeightForWidth())
        self.label_title_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_16.setFont(font)
        self.label_title_16.setAcceptDrops(False)
        self.label_title_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_16.setScaledContents(False)
        self.label_title_16.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_16.setWordWrap(True)
        self.label_title_16.setObjectName("label_title_16")
        self.label_averageNum_16 = QtWidgets.QLabel(self.widget_16)
        self.label_averageNum_16.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_16.setFont(font)
        self.label_averageNum_16.setObjectName("label_averageNum_16")
        self.label_average_16 = QtWidgets.QLabel(self.widget_16)
        self.label_average_16.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_16.setFont(font)
        self.label_average_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_16.setObjectName("label_average_16")
        self.label_cover_16 = QtWidgets.QLabel(self.widget_16)
        self.label_cover_16.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_16.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_16.setText("")
        self.label_cover_16.setObjectName("label_cover_16")
        self.gridLayout_2.addWidget(self.widget_16, 1, 3, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_15.setObjectName("widget_15")
        self.label_title_15 = QtWidgets.QLabel(self.widget_15)
        self.label_title_15.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_15.sizePolicy().hasHeightForWidth())
        self.label_title_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_15.setFont(font)
        self.label_title_15.setAcceptDrops(False)
        self.label_title_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_15.setScaledContents(False)
        self.label_title_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_15.setWordWrap(True)
        self.label_title_15.setObjectName("label_title_15")
        self.label_averageNum_15 = QtWidgets.QLabel(self.widget_15)
        self.label_averageNum_15.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_15.setFont(font)
        self.label_averageNum_15.setObjectName("label_averageNum_15")
        self.label_average_15 = QtWidgets.QLabel(self.widget_15)
        self.label_average_15.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_15.setFont(font)
        self.label_average_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_15.setObjectName("label_average_15")
        self.label_cover_15 = QtWidgets.QLabel(self.widget_15)
        self.label_cover_15.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_15.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_15.setText("")
        self.label_cover_15.setObjectName("label_cover_15")
        self.gridLayout_2.addWidget(self.widget_15, 1, 2, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_13.setObjectName("widget_13")
        self.label_title_13 = QtWidgets.QLabel(self.widget_13)
        self.label_title_13.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_13.sizePolicy().hasHeightForWidth())
        self.label_title_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_13.setFont(font)
        self.label_title_13.setAcceptDrops(False)
        self.label_title_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_13.setScaledContents(False)
        self.label_title_13.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_13.setWordWrap(True)
        self.label_title_13.setObjectName("label_title_13")
        self.label_averageNum_13 = QtWidgets.QLabel(self.widget_13)
        self.label_averageNum_13.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_13.setFont(font)
        self.label_averageNum_13.setObjectName("label_averageNum_13")
        self.label_average_13 = QtWidgets.QLabel(self.widget_13)
        self.label_average_13.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_13.setFont(font)
        self.label_average_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_13.setObjectName("label_average_13")
        self.label_cover_13 = QtWidgets.QLabel(self.widget_13)
        self.label_cover_13.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_13.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_13.setText("")
        self.label_cover_13.setObjectName("label_cover_13")
        self.gridLayout_2.addWidget(self.widget_13, 1, 0, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_11.setObjectName("widget_11")
        self.label_title_11 = QtWidgets.QLabel(self.widget_11)
        self.label_title_11.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_11.sizePolicy().hasHeightForWidth())
        self.label_title_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_11.setFont(font)
        self.label_title_11.setAcceptDrops(False)
        self.label_title_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_11.setScaledContents(False)
        self.label_title_11.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_11.setWordWrap(True)
        self.label_title_11.setObjectName("label_title_11")
        self.label_averageNum_11 = QtWidgets.QLabel(self.widget_11)
        self.label_averageNum_11.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_11.setFont(font)
        self.label_averageNum_11.setObjectName("label_averageNum_11")
        self.label_average_11 = QtWidgets.QLabel(self.widget_11)
        self.label_average_11.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_11.setFont(font)
        self.label_average_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_11.setObjectName("label_average_11")
        self.label_cover_11 = QtWidgets.QLabel(self.widget_11)
        self.label_cover_11.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_11.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_11.setText("")
        self.label_cover_11.setObjectName("label_cover_11")
        self.gridLayout_2.addWidget(self.widget_11, 0, 2, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_12.setObjectName("widget_12")
        self.label_title_12 = QtWidgets.QLabel(self.widget_12)
        self.label_title_12.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_12.sizePolicy().hasHeightForWidth())
        self.label_title_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_12.setFont(font)
        self.label_title_12.setAcceptDrops(False)
        self.label_title_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_12.setScaledContents(False)
        self.label_title_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_12.setWordWrap(True)
        self.label_title_12.setObjectName("label_title_12")
        self.label_averageNum_12 = QtWidgets.QLabel(self.widget_12)
        self.label_averageNum_12.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_12.setFont(font)
        self.label_averageNum_12.setObjectName("label_averageNum_12")
        self.label_average_12 = QtWidgets.QLabel(self.widget_12)
        self.label_average_12.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_12.setFont(font)
        self.label_average_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_12.setObjectName("label_average_12")
        self.label_cover_12 = QtWidgets.QLabel(self.widget_12)
        self.label_cover_12.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_12.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_12.setText("")
        self.label_cover_12.setObjectName("label_cover_12")
        self.gridLayout_2.addWidget(self.widget_12, 0, 3, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_9.setObjectName("widget_9")
        self.label_title_9 = QtWidgets.QLabel(self.widget_9)
        self.label_title_9.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_9.sizePolicy().hasHeightForWidth())
        self.label_title_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_9.setFont(font)
        self.label_title_9.setAcceptDrops(False)
        self.label_title_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_9.setScaledContents(False)
        self.label_title_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_9.setWordWrap(True)
        self.label_title_9.setObjectName("label_title_9")
        self.label_average_9 = QtWidgets.QLabel(self.widget_9)
        self.label_average_9.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_9.setFont(font)
        self.label_average_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_9.setObjectName("label_average_9")
        self.label_averageNum_9 = QtWidgets.QLabel(self.widget_9)
        self.label_averageNum_9.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_9.setFont(font)
        self.label_averageNum_9.setObjectName("label_averageNum_9")
        self.label_cover_9 = QtWidgets.QLabel(self.widget_9)
        self.label_cover_9.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_9.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_9.setText("")
        self.label_cover_9.setObjectName("label_cover_9")
        self.gridLayout_2.addWidget(self.widget_9, 0, 0, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.widget_recommendations)
        self.widget_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_14.setObjectName("widget_14")
        self.label_title_14 = QtWidgets.QLabel(self.widget_14)
        self.label_title_14.setGeometry(QtCore.QRect(10, 160, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_14.sizePolicy().hasHeightForWidth())
        self.label_title_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_title_14.setFont(font)
        self.label_title_14.setAcceptDrops(False)
        self.label_title_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_title_14.setScaledContents(False)
        self.label_title_14.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title_14.setWordWrap(True)
        self.label_title_14.setObjectName("label_title_14")
        self.label_averageNum_14 = QtWidgets.QLabel(self.widget_14)
        self.label_averageNum_14.setGeometry(QtCore.QRect(120, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_averageNum_14.setFont(font)
        self.label_averageNum_14.setObjectName("label_averageNum_14")
        self.label_average_14 = QtWidgets.QLabel(self.widget_14)
        self.label_average_14.setGeometry(QtCore.QRect(20, 220, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_average_14.setFont(font)
        self.label_average_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_average_14.setObjectName("label_average_14")
        self.label_cover_14 = QtWidgets.QLabel(self.widget_14)
        self.label_cover_14.setGeometry(QtCore.QRect(40, 10, 98, 146))
        self.label_cover_14.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.label_cover_14.setText("")
        self.label_cover_14.setObjectName("label_cover_14")
        self.gridLayout_2.addWidget(self.widget_14, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.pushButton_more_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_more_2.setGeometry(QtCore.QRect(290, 620, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_more_2.setFont(font)
        self.pushButton_more_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_more_2.setObjectName("pushButton_more_2")
        self.graphicsView_background_3 = QtWidgets.QGraphicsView(self.page_3)
        self.graphicsView_background_3.setGeometry(QtCore.QRect(-1, -1, 771, 681))
        self.graphicsView_background_3.setStyleSheet("background:url(:/newPrefix/digital-book.jpg)")
        self.graphicsView_background_3.setObjectName("graphicsView_background_3")
        self.graphicsView_background_3.raise_()
        self.label_like.raise_()
        self.widget_recommendations.raise_()
        self.pushButton_more_2.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.books_df = pd.read_csv('dataset/books.csv')
        self.setup()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_getRec.setText(_translate("MainWindow", "Get personal recommendations!"))
        self.label_hello.setText(_translate("MainWindow", "Hello, user"))
        self.label_rate.setText(_translate("MainWindow", "Please, rate the books that you have read"))
        self.pushButton_more.setText(_translate("MainWindow", "Get more books"))
        self.pushButton_done.setText(_translate("MainWindow", "I\'m done, show me recommendations!"))
        self.label_title_1.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_1.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_5.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_5.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_3.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_3.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_4.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_4.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_8.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_8.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_7.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_7.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_6.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_6.setText(_translate("MainWindow", "Your rating:"))
        self.label_title_2.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_rating_2.setText(_translate("MainWindow", "Your rating:"))
        self.label_like.setText(_translate("MainWindow", "You might like..."))
        self.label_title_9.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_average_9.setText(_translate("MainWindow", "Average rating:"))
        self.label_averageNum_9.setText(_translate("MainWindow", "4.0"))
        self.label_title_13.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_13.setText(_translate("MainWindow", "4.0"))
        self.label_average_13.setText(_translate("MainWindow", "Average rating:"))
        self.label_title_11.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_11.setText(_translate("MainWindow", "4.0"))
        self.label_average_11.setText(_translate("MainWindow", "Average rating:"))
        self.label_title_12.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_12.setText(_translate("MainWindow", "4.0"))
        self.label_average_12.setText(_translate("MainWindow", "Average rating:"))
        self.label_title_16.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_16.setText(_translate("MainWindow", "4.0"))
        self.label_average_16.setText(_translate("MainWindow", "Average rating:"))
        self.label_title_15.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_15.setText(_translate("MainWindow", "4.0"))
        self.label_average_15.setText(_translate("MainWindow", "Average rating:"))
        self.label_title_14.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_14.setText(_translate("MainWindow", "4.0"))
        self.label_average_14.setText(_translate("MainWindow", "Average rating:"))
        self.label_title_10.setText(_translate("MainWindow", "This is a very long name of a book that might not even fit"))
        self.label_averageNum_10.setText(_translate("MainWindow", "4.0"))
        self.label_average_10.setText(_translate("MainWindow", "Average rating:"))
        self.pushButton_more_2.setText(_translate("MainWindow", "More!"))

    def setup(self):
        self.pushButton_getRec.clicked.connect(self.switchToSelection)
        self.pushButton_more.clicked.connect(self.getMoreBooks)
        self.pushButton_done.clicked.connect(self.switchToResults)
        self.pushButton_more_2.clicked.connect(self.getMoreBooksRec)

    # switch to page where the user rates books
    def switchToSelection(self):
        #books = get_popular_books()
        #b = books[:8]
        f = h.File('dataset/AL_entropy.hdf5', 'r')
        self.books_to_display = f['AL_books'][:]
        f.close()
        b = self.books_to_display[:8]
        self.books_displayed = 8
        self.current_ids = b
        self.loadBooks(b)
        self.stackedWidget.setCurrentIndex(1)

    # get more books to rate
    def getMoreBooks(self):
        self.saveValues()
        if self.books_displayed == 160:
             self.pushButton_more.setEnabled(False)
             return
        b = self.books_to_display[self.books_displayed:self.books_displayed+8]
        self.books_displayed = self.books_displayed + 8
        self.current_ids = b
        self.clear()
        self.loadBooks(b)

    # switch to the page with recommendations
    def switchToResults(self):
        self.saveValues()
        # if the user didn't rate anything, show the most popular books
        if len(self.user_ratings) == 0:
            f = h.File('dataset/AL_popularity.hdf5', 'r')
            best_books = f['AL_books'][:]
            f.close()
            self.recommended_books = best_books[:80]
        else:
            rec = recommender.Recommender()
            self.recommended_books = rec.getRecommendations(self.user_ratings)
            
        self.rec_books_num = len(self.recommended_books)
        self.displayResults(self.recommended_books[:8])
        self.rec_books_displayed = 8
        self.stackedWidget.setCurrentIndex(2)

    # clear ratings (when the user loads more books)
    def clear(self):
        self.spinBox_rating_1.setValue(0)
        self.spinBox_rating_2.setValue(0)
        self.spinBox_rating_3.setValue(0)
        self.spinBox_rating_4.setValue(0)
        self.spinBox_rating_5.setValue(0)
        self.spinBox_rating_6.setValue(0)
        self.spinBox_rating_7.setValue(0)
        self.spinBox_rating_8.setValue(0)

    # load books to rate
    def loadBooks(self, b):
        image = QtGui.QImage()
        image.load('img/' + str(b[0]), ".jpg")
        self.label_cover_1.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[0]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_1.setText(str(title))

        image.load('img/' + str(b[1]), ".jpg")
        self.label_cover_2.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[1]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_2.setText(str(title))

        image.load('img/' + str(b[2]), ".jpg")
        self.label_cover_3.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[2]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_3.setText(str(title))

        image.load('img/' + str(b[3]), ".jpg")
        self.label_cover_4.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[3]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_4.setText(str(title))
        
        image.load('img/' + str(b[4]), ".jpg")
        self.label_cover_5.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[4]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_5.setText(str(title))
        
        image.load('img/' + str(b[5]), ".jpg")
        self.label_cover_6.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[5]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_6.setText(str(title))
        
        image.load('img/' + str(b[6]), ".jpg")
        self.label_cover_7.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[6]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_7.setText(str(title))
        
        image.load('img/' + str(b[7]), ".jpg")
        self.label_cover_8.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[7]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_8.setText(str(title))

    # save the input
    def saveValues(self):
        if self.spinBox_rating_1.value() != 0:
            self.user_ratings.append((self.current_ids[0], self.spinBox_rating_1.value()))
        if self.spinBox_rating_2.value() != 0:
            self.user_ratings.append((self.current_ids[1], self.spinBox_rating_2.value()))
        if self.spinBox_rating_3.value() != 0:
            self.user_ratings.append((self.current_ids[2], self.spinBox_rating_3.value()))
        if self.spinBox_rating_4.value() != 0:
            self.user_ratings.append((self.current_ids[3], self.spinBox_rating_4.value()))
        if self.spinBox_rating_5.value() != 0:
            self.user_ratings.append((self.current_ids[4], self.spinBox_rating_5.value()))
        if self.spinBox_rating_6.value() != 0:
            self.user_ratings.append((self.current_ids[5], self.spinBox_rating_6.value()))
        if self.spinBox_rating_7.value() != 0:
            self.user_ratings.append((self.current_ids[6], self.spinBox_rating_7.value()))
        if self.spinBox_rating_8.value() != 0:
            self.user_ratings.append((self.current_ids[7], self.spinBox_rating_8.value()))
        #print(self.user_ratings)

    # get more books recommended
    def getMoreBooksRec(self):
        if self.rec_books_displayed == self.rec_books_num:
             self.pushButton_more_2.setEnabled(False)
             return
        b = self.recommended_books[self.rec_books_displayed:self.rec_books_displayed+8]
        self.rec_books_displayed = self.rec_books_displayed + 8
        self.displayResults(b)

    # display recommendations
    def displayResults(self, b):
        image = QtGui.QImage()
        image.load('img/' + str(b[0]), ".jpg")
        self.label_cover_9.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[0]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_9.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_9.setText(str(average_rating))

        image.load('img/' + str(b[1]), ".jpg")
        self.label_cover_10.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[1]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_10.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_10.setText(str(average_rating))

        image.load('img/' + str(b[2]), ".jpg")
        self.label_cover_11.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[2]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_11.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_11.setText(str(average_rating))

        image.load('img/' + str(b[3]), ".jpg")
        self.label_cover_12.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[3]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_12.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_12.setText(str(average_rating))
        
        image.load('img/' + str(b[4]), ".jpg")
        self.label_cover_13.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[4]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_13.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_13.setText(str(average_rating))
        
        image.load('img/' + str(b[5]), ".jpg")
        self.label_cover_14.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[5]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_14.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_14.setText(str(average_rating))
        
        image.load('img/' + str(b[6]), ".jpg")
        self.label_cover_15.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[6]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_15.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_15.setText(str(average_rating))
        
        image.load('img/' + str(b[7]), ".jpg")
        self.label_cover_16.setPixmap(QtGui.QPixmap(image))
        row = self.books_df.loc[self.books_df['id'] == b[7]]
        row = next(row.iterrows())[1]
        title = row['title']
        self.label_title_16.setText(str(title))
        average_rating = row['average_rating']
        self.label_averageNum_16.setText(str(average_rating))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

